## ---- eval = FALSE-------------------------------------------------------
#  devtools::create(path = "D:/Github/metodosMultivariados2017")

## ---- eval = FALSE-------------------------------------------------------
#  timesTwo <- function(x) {
#    2*x
#  }

## ---- eval = FALSE-------------------------------------------------------
#  # esta funcion multiplica por dos
#  timesTwo <- function(x) {
#    2*x
#  }

## ---- eval = FALSE-------------------------------------------------------
#  #' @title Multiplicar por dos
#  #' @description Esta es una funcion de ejemplo para multiplicar un valor o vector \code{x} por dos.
#  #' @param x un elemento o vector numerico
#  #' @details Esta funcion es parte del tutorial para hacer paquetes del curso de Metodos Multivariados 2017
#  #' en el ITAM. La funcion recibe un elemento \code{x} que puede ser un numero o un vector numerico y lo devuelve
#  #' multiplicado por dos. La documentacion de ayuda es generada usando roxygen2.
#  #' @examples
#  #' timesTwo(3)
#  #' timesTwo(0:10)
#  #' @export
#  timesTwo <- function(x) {
#    2*x
#  }
#  

## ---- eval = FALSE, echo = FALSE-----------------------------------------
#  devtools::document()
#  devtools::install()

## ------------------------------------------------------------------------
library(metodosMultivariados2017)
timesTwo(3)

## ------------------------------------------------------------------------
example(timesTwo)

## ---- eval = FALSE-------------------------------------------------------
#  help(package = "metodosMultivariados2017")

## ---- eval = FALSE-------------------------------------------------------
#  help(timesTwo)

## ---- eval  = FALSE------------------------------------------------------
#  # Generated by roxygen2: do not edit by hand
#  
#  export(timesTwo)

## ---- eval = FALSE-------------------------------------------------------
#  #' @import magrittr
#  #' @title Multiplicar por cuatro
#  #' @description Esta es una funcion de ejemplo para multiplicar un valor o vector x por cuatro.
#  #' @param x un elemento o vector numerico
#  #' @details Esta funcion es parte del tutorial para hacer paquetes del curso de Metodos Multivariados 2017
#  #' en el ITAM. La funcion recibe un elemento x que puede ser un numero o un vector numerico y lo devuelve
#  #' multiplicado por cuatro. La documentacion de ayuda es generada usando roxygen2. La implementacion utiliza \code{\link{timesTwo}}
#  #' @examples
#  #' timesFour(3)
#  #' timesFour(0:10)
#  #' @export
#  timesFour <- function(x) {
#    x %>% timesTwo() %>% timesTwo()
#  }
#  

## ---- eval = FALSE-------------------------------------------------------
#  devtools::document()
#  devtools::install()

## ------------------------------------------------------------------------
example(timesFour)

## ---- eval = FALSE-------------------------------------------------------
#  # Generated by roxygen2: do not edit by hand
#  
#  export(timesFour)
#  export(timesTwo)
#  import(magrittr)

## ---- eval = FALSE-------------------------------------------------------
#  devtools::install_github("mauriciogtec/metodosMultivariados2017")

